### ISSUE TITLE
 Please implement the Stateless OpenPGP ("SOP") interface

### ISSUE THREAD

**Issue by dkg** [btrott/Crypt-OpenPGP#36]
[the Stateless OpenPGP command line interface](https://datatracker.ietf.org/doc/draft-dkg-openpgp-stateless-cli/) (aka `sop`) is useful for [testing interoperability with other OpenPGP implementations](https://tests.sequoia-pgp.org/).

It would be great if Crypt::OpenPGP could provide this interface.

see also https://gitlab.com/sequoia-pgp/openpgp-interoperability-test-suite/-/issues/53

**Comment by timlegge** [comment]
I have taken over as module maintainer and moved the git repo to https://github.com/perl-Crypt-OpenPGP/Crypt-OpenPGP.  I have been cleaning up old issues and not really ready to take on more at the moment but happy to discuss or revised pull requests at the new repo

**Comment by dkg** [comment]
I'll close this now in favor of https://github.com/perl-Crypt-OpenPGP/Crypt-OpenPGP/issues/4
