### ISSUE TITLE
Please implement support for RFC9580 (obsoletes RFC4880)

### ISSUE THREAD

**Issue by guillemj** [btrott/Crypt-OpenPGP#37]
The OpenPGP Working Group has recently released an update to the RFC as [RFC9580](https://www.rfc-editor.org/rfc/rfc9580.html) which obsoletes RFC4880, it would be nice to get this module updated to support the new spec.

There's also an interoperability test suite at https://tests.sequoia-pgp.org/, that could be helpful to test the implementation conformance.

**Comment by timlegge** [comment]
I have taken over as module maintainer and moved the git repo to https://github.com/perl-Crypt-OpenPGP/Crypt-OpenPGP.  I have been cleaning up old issues and not really ready to take on more at the moment but happy to discuss or revised pull requests at the new repo

**Comment by guillemj** [comment]
Ah, it's great that this module is now maintained! If you don't mind I think it would make sense to file this into the new repo, there are not many implementations fully compliant, but I think at some point it will be relevant, so it would be nice to have a place to track the status and or interest, etc.

**Comment by guillemj** [comment]
I'm closing this in favor of perl-Crypt-OpenPGP#5
