### ISSUE TITLE
Issue with standard encrypted data packets

### ISSUE THREAD

**Issue by throughnothing** [btrott/Crypt-OpenPGP#7]
I have made a gist which exmemplifies the issue:

https://gist.github.com/3361655

I believe the issue occurs because of `pack` calls that are cutting off excess bytes in certain cases. I'm not sure the exact solution, but the gist above should be able to reproduce the problem, so hopefully that helps.

I have tested this on Intel x86_64 architectures, but did not have a 32-bit machine to try it on.

**Comment by Camspi** [comment]
Pull request #27 resolves this issue.
